version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local
    entrypoint: java
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /data'
    restart: always
    ports:
      - 8042:8000
    volumes:
      - $PWD/dynamodb:/data