version: '3.7'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=docker
    networks:
      - mongodb-compose-network

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongodb-compose-network

networks:
  mongodb-compose-network:
    driver: bridge