version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      # user é sa
      - SA_PASSWORD=sateste
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - ${PWD}/mssql:/var/opt/mssql
    networks:
      - mssql-compose-network
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mssql-compose-network

networks:
  mssql-compose-network:
    driver: bridge