version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306